"""HTML -> PDF rendering of reports with WeasyPrint."""
from __future__ import annotations
import io
from typing import Dict, List, Sequence

from jinja2 import Template

_TEMPLATE = Template("""
<!doctype html>
<html><head><meta charset="utf-8">
<style>
  @page { size: A4 landscape; margin: 1.5cm; }
  body { font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif; color: #2E2E38; font-size: 10px; }
  h1 { color: #543FDE; font-size: 18px; margin: 0 0 4px; }
  .meta { color: #65657B; font-size: 10px; margin-bottom: 12px; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #FAFAFA; text-align: left; padding: 6px; border-bottom: 2px solid #543FDE; font-size: 10px; }
  td { padding: 5px 6px; border-bottom: 1px solid #E0E0E0; font-size: 9px; }
  tr:nth-child(even) td { background: #FBFBFD; }
  .footer { margin-top: 16px; color: #8F8FA3; font-size: 8px; }
</style></head>
<body>
  <h1>{{ title }}</h1>
  <div class="meta">Snapshot {{ snapshot_id }} &middot; taken {{ taken_at }} by {{ taken_by }} &middot; {{ row_count }} rows</div>
  <table>
    <thead><tr>{% for c in columns %}<th>{{ c.label }}</th>{% endfor %}</tr></thead>
    <tbody>
      {% for row in rows %}
        <tr>{% for c in columns %}<td>{{ row.get(c.key) if row.get(c.key) is not none else '—' }}</td>{% endfor %}</tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="footer">Generated by Domino Permissions Audit &middot; for GxP periodic access review (21 CFR Part 11 / Annex 11 / GAMP 5)</div>
</body></html>
""")


def render_pdf(title: str, snapshot_meta: Dict, columns: Sequence[Dict], rows: List[Dict]) -> bytes:
    from weasyprint import HTML  # imported lazily so dev without weasyprint still loads

    html = _TEMPLATE.render(
        title=title,
        snapshot_id=snapshot_meta.get("id", "—"),
        taken_at=snapshot_meta.get("takenAt", "—"),
        taken_by=snapshot_meta.get("takenBy", "—"),
        row_count=len(rows),
        columns=columns,
        rows=rows,
    )
    buf = io.BytesIO()
    HTML(string=html).write_pdf(buf)
    return buf.getvalue()
